version: '3.8'

services:
  base:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USERNAME: ${USERNAME}
        USER_PASSWORD: ${USER_PASSWORD}
        ROOT_PASSWORD: ${ROOT_PASSWORD}
    env_file:
      - .env
    volumes:
      - type: bind
        source: ../app
        target: /app
    tty: true
    container_name: "${CONTAINER_NAME}"