version: '3.8'

services:
  base:
    build:
        context: .
        dockerfile: Dockerfile
    volumes:
      - ../app:/app
      - /home/nemu/.ssh/id_ed25519:/.ssh/id_ed25519
    container_name: "test"