version: '3.8'

services:
  base:
    build:
        context: .
        dockerfile: Dockerfile
    volumes:
      - ../app:/app
      - /home/nemu/.ssh:/.ssh
    tty: true
    container_name: "${CONTAINER_NAME}"